apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: backend-deployment
  updatePolicy:
    updateMode: "Off" # Set to "Auto" for automatic updates(Overrides HPA limits), "Off" to disable updates
